version: '3.8'
services:
  db:
    container_name: db
    ports:
      - '5432:5432'
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - ${POSTGRES_USER}
      - ${POSTGRES_PASSWORD}
      - POSTGRES_DB=photo_contest
      - POSTGRES_HOST_AUTH_METHOD= "trust"
    networks:
      - photo-contest-network

  server:
    build: ./backend
    container_name: express
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - /app/node_modules
      - ./backend:/app
    env_file:
      - .env
    environment:
      - ${POSTGRES_USER}
      - ${POSTGRES_PASSWORD}
      - POSTGRES_DB=photo_contest
      - ${TOKEN_SECRET}
    networks:
      - photo-contest-network


  client:
    build: ./frontend
    container_name: react
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - photo-contest-network

networks:
  photo-contest-network:
    driver: bridge
